name: sample
description: balhs
version: 0.0.1

services:
  web:
    location: ./web-server
  mongo:
    location: ../mongo
    url: https://github.com/Originate/exosphere-mongodb-service.git
  users:
    location: ../exosphere-users-service
    url: https://github.com/Originate/exosphere-users-service
  tweets:
    location: ../exosphere-mongodb-service
    url: https://github.com/Originate/exosphere-tweets-service.git
