name: sample
description: balhs
version: 0.0.1

services:
  web:
    local: ./web-server
  mongo:
    local: ./exosphere-mongodb-service
    origin: https://github.com/Originate/exosphere-mongodb-service.git
  users:
    local: ./exosphere-users-service
    origin: https://github.com/Originate/exosphere-users-service
  tweets:
    local: ./exosphere-mongodb-service
    origin: https://github.com/Originate/exosphere-tweets-service.git
  no-service:
    local: ./Spoon-Knife
    origin: https://github.com/hubot/Spoon-Knife.git
  bad-service:
    local: ./hello-world
    origin: https://github.com/leachim6/hello-world.git
