name: mongo
description: asldkfja

setup: npm install --loglevel error --depth 0
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/cucumber/bin/cucumber.js

messages:
  receives:
    - mongo.create
    - mongo.create_many
    - mongo.delete
    - mongo.list
    - mongo.read
    - mongo.update
  sends:
    - mongo.created
    - mongo.created_many
    - mongo.deleted
    - mongo.listing
    - mongo.details
    - mongo.updated
